abc

diff --git a/.github/workflows/release-plz.yml b/.github/workflows/release-plz.yml
--- a/.github/workflows/release-plz.yml
+++ b/.github/workflows/release-plz.yml
@@ -44,7 +44,8 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
         run: |
-          set -x
+          set -eu
+
           pr_branch_name="${{ fromJSON(steps.release-plz.outputs.pr).head_branch }}"
 
           # switch to the branch created by release-plz
@@ -82,11 +83,15 @@ jobs:
             { commit { commitUrl } }
           }"}'
           # create new commit with changes
-          curl https://api.github.com/graphql \
+          result=$(curl -sS https://api.github.com/graphql \
             -H "Accept: application/vnd.github+json" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer ${GITHUB_TOKEN}" \
-            --data "$(echo "$query" | tr -d '\n')"
+            --data "$(echo "$query" | tr -d '\n')")
+
+          if $(echo "$result" | jq -e '.errors | length != 0'); then
+            echo "Commit failed: $(echo "$result" | jq '.errors')"
+          fi
 
       - name: Release to npm
         env:
